### ISSUE TITLE
MultiSelect fails when isMulti is set to false

### ISSUE THREAD

**Issue by bmilhollin** [CompositionalIT/Feliz.ReactSelect#1]
When ReactSelect.isMulti is set to false, the onChange is expecting a Choice array, but instead receives a Choice.  As a result, the value of the selection is not returned.

We were able to create a workaround as follows after opening Fable.Core.JsInterop.

```fsharp
ReactSelect.create [
    ReactSelect.placeholder 
        (if loadingState then "Loading Customers" else "Select Customer")
    ReactSelect.isLoading loadingState
    ReactSelect.isSearchable true
    ReactSelect.isMulti false
    ReactSelect.options customerOptions
    ReactSelect.menuPlacement Bottom
    ReactSelect.onChange (fun (choices: Choice []) -> dispatch (SetCustomerName { Label = choices?label; Value = choices?value }))
]
```

**Comment by theprash** [comment]
There are a few ways this wrapper could change to accommodate the dynamic nature of `react-select`. The simplest change here might be to convert a single choice into an array containing one choice, and it's also backwards compatible.

**Comment by isaacabraham** [comment]
We could also just add an overload

**Comment by theprash** [comment]
Yes that would work. I think then the overload of `onChange` should take a function that takes `Choice option`.

**Comment by Tom-Sloboda** [comment]
https://github.com/CompositionalIT/Feliz.ReactSelect/commit/f2c712e218e1c925a42d4bbf1735fd673ac0b708

Added an overload that takes Choice option.
